### PR TITLE
removing xdebug as it's unused

### PR DESCRIPTION
**Pull request by alackmann**
Should this be a seperate branch? Different repo? Is there a better way to make this optional?

### CODE REVIEW

**Comment by zakhenry** [comment]
@alackmann yes, I would prefer implementation that allows for temporary xdebug disabling for composer, see https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer for good examples on setting up aliases to have xdebug toggled for php

**Comment by iquitsugar** [comment]
@xiphiaz have updated to have helper scripts for xdebug on/off and implemented a wrapper for composer to ensure xdebug is off when run and enabled again on completion.

**Comment by alackmann** [comment]
@xiphiaz have updated to have helper scripts for xdebug on/off and implemented a wrapper for composer to ensure xdebug is off when run and enabled again on completion.

**Comment by zakhenry** [comment]
@alackmann yep that's nicer, better to have the option

**Pull request merged**
